on: 
  workflow_call:
    inputs:
      node_version:
        required: true
        default: 18
        type: number
      repository:
        required: false
        default: "test"
        type: string
      files:
        required: false
        default: "node_modules public package.lock.json"
        type: string
jobs:
  npm-install:
    name: npm-install
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version:  ${{ inputs.node_version }}

    - name: Install Dependencies
      run: |
        npm install

    - name: Zip files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r files.zip ${{ inputs.files }}

    - name: Upload node-modules
      uses: actions/upload-artifact@v3
      with:
        name: files
        path: files.zip
