on: 
  workflow_call:
    inputs:
      node_version:
        required: true
        type: number

jobs:
  npm-install:
    name: npm-install
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version:  ${{ inputs.node_version }}

    - name: Install Dependencies
      run: |
        npm install