on: 
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
    secrets:
      AWS_ACCESS_ROLE:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_DISTRIBUTION_ID:
        required: true
      AWS_S3_BUCKET:
        required: true
      BUILD_DIR:
        required: true

jobs:
  apply:
    name: aws-cloudfront
    env:
      BUILD_DIR: ${{ secrets.BUILD_DIR }}
      AWS_DISTRIBUTION_ID:  ${{ secrets.AWS_DISTRIBUTION_ID }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: Download Build
      uses: actions/download-artifact@v3
      with:
        name: build

    - uses: montudor/action-zip@v1
      with:
        args: unzip -qq build.zip -d build

    - name: Check
      run: ls -lh

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ACCESS_ROLE }}
        role-session-name: github-action-job
        role-duration-seconds: 900
        aws-region: us-east-1

    - name: Sync S3 Bucket
      run: |
        echo "Save in S3 Bucket"
        aws s3 sync build/${BUILD_DIR} $AWS_S3_BUCKET

    - name: Deploy Invalidation 
      run: |
        echo "Deploy to Cloudfront"
        aws cloudfront create-invalidation --paths /* --distribution-id $AWS_DISTRIBUTION_ID
