on: 
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      URL_S3_BUCKET:
        required: true
      DISTRIBUTION_ID:
        required: true

jobs:
  apply:
    name: aws-cloudfront
    env:
      NPM_BUILD_DIR: ./build/
      DISTRIBUTION_ID:  ${{ secrets.DISTRIBUTION_ID }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v1

    - uses: actions/setup-node@v3
      with:
        node-version: current

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Install Dependencies
      run: |
        npm install

    - name: Build Gatsby App
      run: |
        gatsby build        

    - name: Sync S3 Bucket
      run: |
        echo "Save in S3 Bucket"
        aws s3 sync $NPM_BUILD_DIR $URL_S3_BUCKET

    - name: Deploy Invalidation 
      run: |
        echo "Deploy to Cloudfront"
        aws cloudfront create-invalidation --paths /* --distribution-id $DISTRIBUTION_ID
