on: 
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
    secrets:
      AWS_ACCESS_ROLE:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_DISTRIBUTION_ID:
        required: true
jobs:
  apply:
    name: aws-cloudfront
    env:
      NPM_BUILD_DIR: ./build/
      AWS_DISTRIBUTION_ID:  ${{ secrets.AWS_DISTRIBUTION_ID }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v1

    - uses: actions/setup-node@v3
      with:
        node-version: current

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ACCESS_ROLE }}
        role-session-name: github-action-job
        role-duration-seconds: 900
        aws-region: us-east-1

    - name: Install Dependencies
      run: |
        npm install
        npm i -g  gatsby-cli

    - name: Build Gatsby App
      run: |
        gatsby build  

    - name: Sync S3 Bucket
      run: |
        echo "Save in S3 Bucket"
        aws s3 sync $NPM_BUILD_DIR $URL_S3_BUCKET

    - name: Deploy Invalidation 
      run: |
        echo "Deploy to Cloudfront"
        aws cloudfront create-invalidation --paths /* --distribution-id $AWS_DISTRIBUTION_ID
