on: 
  workflow_call:
    inputs:
      repository:
        required: false
        type: string
jobs:
  install:
    uses: ./.github/workflows/node/install.yml@main
    inputs:
      node_version: 18
