name: Main Terraform
on: 
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
jobs:
  terraform-validate:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-validate.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  terraform-plugin-tfsec:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-plugin-tfsec.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  terraform-plugin-tfdocs:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-plugin-tfdocs.yml@main 
