on: 
  workflow_call:
    inputs:
      repository:
        required: false
        type: string
jobs:
  npm-install:
    name: npm-install
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_ROLE: ${{ secrets.AWS_ACCESS_ROLE }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: current

    - name: Install Dependencies
      run: |
        npm install

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r node_modules.zip node_modules

    - name: Upload node-modules
      uses: actions/upload-artifact@v3
      with:
        name: node_modules
        path: node_modules.zip