on: 
  workflow_call:
    inputs:
      repository:
        required: false
        type: string

jobs:
  apply:
    name: npm-build-nextjs
    env:
      BUILD_DIR: .next/

    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Next
      run: |
        npm install
        npm i -g next

    - name: Build NextJs App
      run: |
        npm run build --if-present 

    - name: Check
      run: | 
        ls -lh

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r build.zip .next/

    - name: Upload node-modules
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.zip