on: 
  workflow_call:
    inputs:
      repositoryUrl:
        type: string
        required: true
    secrets:
      token:
        required: true
jobs:
  semantic-release:
    name: semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        id: semantic-release
        uses: codfish/semantic-release-action@v1
        with:
          dry_run: true
          repository_url: ${{ inputs.repositoryUrl }}
          tag_format: 'v${version}'
          extra_plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github']
          branches: |    
            [
              'main', 
              'next-major', 
              {
                name: 'beta', 
                prerelease: true
              }, 
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          
      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}