on: 
  workflow_call:
    inputs:
      repositoryUrl:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true
jobs:
  semantic-release:
    name: semantic-release
    runs-on: ubuntu-latest
    steps:
      - run: codfish/semantic-release-action@v1
        with:
          dry_run: true
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          tag_format: 'v${version}'
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/npm', '@semantic-release/github']
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}