on: 
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v1

    - name: Run a Terraform validate    
      uses: hashicorp/terraform-github-actions@master
      with:
        entrypoint: terraform
        args: validate
