on: 
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
jobs:
  fmt:
    name: FMT
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: Run a Terraform init 
      run:
        terraform init

    - name: Run a Terraform fmt    
      run:
        terraform fmt .

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: '.'
        message: 'Format Terraform'
