on: 
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
    secrets:
      AWS_ACCESS_ROLE:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: false

jobs:
  terraform-plugin-terratest:
    name: terraform-plugin-terragrunt-fmt
    runs-on: ubuntu-latest
    steps:
    - name: Validate if Exists Env Vars
      id: check
      run: | 
        if [[ -z "${{ secrets.AWS_ACCESS_ROLE }}" ]]; then
          exit 1
        else
          echo "Yes Sir"
        fi
        
        if [[ -z "${{ secrets.AWS_DEFAULT_REGION }}" ]]; then
          exit 1
        else
          echo "Yes Sir"
        fi

    - name: Check out code
      if: steps.check.outcome != 'failure'
      uses: actions/checkout@v2

    - name: Set up Go
      if: steps.check.outcome != 'failure'
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Configure AWS credentials
      if: steps.check.outcome != 'failure'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ACCESS_ROLE }}
        role-session-name: github-action-job
        role-duration-seconds: 900
        aws-region: us-east-1

    - name: Run test
      if: steps.check.outcome != 'failure'
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: | 
        cd tests/
        go mod tidy
        go test -v  -timeout 30m
