on: 
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
    secrets:
      AWS_ACCESS_ROLE:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  terraform-plugin-terragrunt-fmt:
    name: terraform-plugin-terragrunt-fmt
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.36.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ACCESS_ROLE }}
        role-session-name: github-action-job
        role-duration-seconds: 900
        aws-region: us-east-1

    - name: Initialized    
      run: terragrunt run-all init  -input=false 

    - name: Run a Terraform fmt    
      run:
        terraform fmt .

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: '.'
        message: 'Format Terraform'
