name: Check Security in Terraform files
on: 
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
jobs:
  terraform-plugin-tfsec:
    name: terraform-plugin-tfsec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: tfsec
      uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
      with:
        github_token: ${{ secrets.GH_TOKEN }}
